javaaddpath('/home/deadlock/Files/Configuraciones/mysql/mariadb-java-client-3.5.8.jar')
                                                                                                                                                                                        
  connexion = database( ...
      'matlab', ...                                                                                                                                                                     
      'workbench', ...
      'workbench', ...
      'org.mariadb.jdbc.Driver', ...                                                                                                                                                    
      'jdbc:mariadb://127.0.0.1:3306/matlab' ...
  );                                                                                                                                                                                    
                  
  if isopen(connexion)
      disp('Conexión exitosa')
  else                                                                                                                                                                                  
      disp(connexion.Message)
  end      