%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace.

% Auto-generated by MATLAB (R2025b) and Database Toolbox Version 25.2 on 06-Apr-2026 19:13:48
function [resultado] =  consultaDato ()
%% Make connection to database
  conn = database( ...
      'matlab', ...                                                                                                                                                                     
      'workbench', ...
      'workbench', ...
      'org.mariadb.jdbc.Driver', ...                                                                                                                                                    
      'jdbc:mariadb://127.0.0.1:3306/matlab' ...
  );                       

%Set query to execute on the database
query = ['SELECT ID_DATO, VALOR_X, VALOR_Y ' ...
    'FROM matlab.dato WHERE ESTADO=1 ORDER BY ID_DATO DESC'];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query
if isstruct (data)
    resultado = struct2table(data);
elseif iscell(data)
    resultado = cellt2table(data);
else 
    resultado = data;
end