function insertarDato(valueX, valueY, idUser)
    connexion = database( ...
      'matlab', ...                                                                                                                                                                     
      'workbench', ...
      'workbench', ...
      'org.mariadb.jdbc.Driver', ...                                                                                                                                                    
      'jdbc:mariadb://127.0.0.1:3306/matlab' ...
    )                                                                                                                                                                                    
    query = sprintf( ...
        ['INSERT INTO dato (ESTADO, VALOR_X, VALOR_Y, ID_USUARIO) ' ...
        '        VALUES (%d, %.2f, %.2f, %d);'], 1, valueX, valueY, idUser ...
        )
    execute(connexion, query)
    close(connexion);
    clear connexion query
end