function modificarDato(idData, value_X, value_Y)
    connexion = database( ...
      'matlab', ...                                                                                                                                                                     
      'workbench', ...
      'workbench', ...
      'org.mariadb.jdbc.Driver', ...                                                                                                                                                    
      'jdbc:mariadb://127.0.0.1:3306/matlab' ...
    )                                                                                                                                                                                    
    query = sprintf( ...
        'UPDATE dato SET VALOR_X=%.2f, VALOR_Y=%.2f WHERE ID_DATO=%d', ...
        value_X, value_Y, idData ...
        );
    execute(connexion, query)
    close(connexion);
    clear connexion query
end